###
GET http://localhost:3000/
Content-Type: application/json

###
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "deodorant",
    "quantity": 20,
    "price": 5,
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/9b/Handmade_soap_cropped_and_simplified.jpg"
} 
###
GET http://localhost:3000/api/products
Content-Type: application/json


###
GET http://localhost:3000/api/products/64fdcea57fbaa5557c2fd334
Content-Type: application/json

###
GET http://localhost:3000/api/products/asds
Content-Type: application/json

###
PUT http://localhost:3000/api/products/6502b90af4a0fb9812f7f6c6
Content-Type: application/json

{"name" : "deodorant-ultra"}

###
PUT http://localhost:3000/products/64fdcebf7fbaa5557c2fd336
Content-Type: application/x-www-form-urlencoded

name=shampoo&price=33

###
DELETE http://localhost:3000/api/products/sdf
Content-Type: application/json